version: 0.0
os: linux
files:
  - source: /

hooks:
  ApplicationStop:
    - location: scripts/stop_container.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 1200
      runas: root
  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 300
      runas: root
