version: 0.2

phases:
  install:
    commands:
      - echo "Installing OWASP ZAP..."
      - curl -sLo zap.tar.gz https://github.com/zaproxy/zaproxy/releases/download/v2.16.1/ZAP_2.16.1_Linux.tar.gz
      - tar -xzf zap.tar.gz -C /opt
      - export ZAP_HOME=/opt/ZAP_2.16.1
      - export PATH=$ZAP_HOME:$PATH

  build:
    commands:
      - echo "Running OWASP ZAP API scan on $API_URL..."
      - mkdir -p /tmp/reports
      - $ZAP_HOME/zap.sh -cmd -quickurl $API_URL -quickout /tmp/reports/zap_report.json
      - ls -lah /tmp/reports/
      - echo "Uploading report to S3..."
      - aws s3 cp /tmp/reports/zap_report.json s3://$REPORT_BUCKET/zap_report_$(date +%F_%T).json

  post_build:
    commands:
      - echo "OWASP ZAP scan completed."
      
artifacts:
  files:
    - reports/zap_report.json
  discard-paths: no
  base-directory: reports/
