version: 0.2

phases:
  install:
    runtime-versions:
      java: 17
    commands:
      - echo "Installing Maven..."
      - curl -sL https://downloads.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz -o maven.tar.gz
      - tar -xvzf maven.tar.gz
      - mv apache-maven-3.9.6 /opt/maven
      - export PATH=/opt/maven/bin:$PATH
      - mvn -version
      - echo "Building the Spring Boot application"
      - cd Order-Service
      - mvn clean package -DskipTests

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
  build:
    commands:
      - cd ..
      - echo Building the Docker image...
      - docker build -t order-service ./Order-Service
      - docker tag order-service:latest $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push $REPOSITORY_URI:latest
      - echo "Image pushed to $REPOSITORY_URI"
      
artifacts:
  files:
    - '**/*'
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'